services:
    # image project
    app:
        build:
            args:
                user: precpago
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: precpago/laravel-api
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-api

    # nginx
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - 8989:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel-api

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel-api

networks:
    laravel-api:
        driver: bridge
